ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=5)

      DOUBLE PRECISION MDL_MH,MDL_MZ,MDL_MT,MDL_MW

      COMMON/MASSES/ MDL_MH,MDL_MZ,MDL_MT,MDL_MW


      DOUBLE PRECISION MDL_WZ,MDL_WH,MDL_WW,MDL_WT

      COMMON/WIDTHS/ MDL_WZ,MDL_WH,MDL_WW,MDL_WT


      DOUBLE COMPLEX GC_358, GC_360, GC_10, GC_11, GC_12, GC_109,
     $  GC_110, GC_112, GC_113, GC_30, GC_31, GC_32, GC_34, GC_35,
     $  GC_71, GC_72, GC_83, GC_85, GC_86, GC_87, GC_88, GC_89, GC_90,
     $  GC_195

      COMMON/COUPLINGS/ GC_358, GC_360, GC_10, GC_11, GC_12, GC_109,
     $  GC_110, GC_112, GC_113, GC_30, GC_31, GC_32, GC_34, GC_35,
     $  GC_71, GC_72, GC_83, GC_85, GC_86, GC_87, GC_88, GC_89, GC_90,
     $  GC_195

