
# For python linking (require f2py part of numpy)
ifeq ($(origin MENUM),undefined)
  MENUM=2
endif
P1_gg_ttxg/matrix$(MENUM)py.so:
	cd P1_gg_ttxg;make matrix$(MENUM)py.so
P1_gu_ttxu/matrix$(MENUM)py.so:
	cd P1_gu_ttxu;make matrix$(MENUM)py.so
P1_gc_ttxc/matrix$(MENUM)py.so:
	cd P1_gc_ttxc;make matrix$(MENUM)py.so
P1_gd_ttxd/matrix$(MENUM)py.so:
	cd P1_gd_ttxd;make matrix$(MENUM)py.so
P1_gb_ttxb/matrix$(MENUM)py.so:
	cd P1_gb_ttxb;make matrix$(MENUM)py.so
P1_gux_ttxux/matrix$(MENUM)py.so:
	cd P1_gux_ttxux;make matrix$(MENUM)py.so
P1_gcx_ttxcx/matrix$(MENUM)py.so:
	cd P1_gcx_ttxcx;make matrix$(MENUM)py.so
P1_gdx_ttxdx/matrix$(MENUM)py.so:
	cd P1_gdx_ttxdx;make matrix$(MENUM)py.so
P1_gbx_ttxbx/matrix$(MENUM)py.so:
	cd P1_gbx_ttxbx;make matrix$(MENUM)py.so
P1_uux_ttxg/matrix$(MENUM)py.so:
	cd P1_uux_ttxg;make matrix$(MENUM)py.so
P1_ccx_ttxg/matrix$(MENUM)py.so:
	cd P1_ccx_ttxg;make matrix$(MENUM)py.so
P1_ddx_ttxg/matrix$(MENUM)py.so:
	cd P1_ddx_ttxg;make matrix$(MENUM)py.so
P1_bbx_ttxg/matrix$(MENUM)py.so:
	cd P1_bbx_ttxg;make matrix$(MENUM)py.so
P0_gg_ttx/matrix$(MENUM)py.so:
	cd P0_gg_ttx;make matrix$(MENUM)py.so
P0_uux_ttx/matrix$(MENUM)py.so:
	cd P0_uux_ttx;make matrix$(MENUM)py.so
P0_ccx_ttx/matrix$(MENUM)py.so:
	cd P0_ccx_ttx;make matrix$(MENUM)py.so
P0_ddx_ttx/matrix$(MENUM)py.so:
	cd P0_ddx_ttx;make matrix$(MENUM)py.so
P0_bbx_ttx/matrix$(MENUM)py.so:
	cd P0_bbx_ttx;make matrix$(MENUM)py.so
all:  P1_gg_ttxg/matrix$(MENUM)py.so  P1_gu_ttxu/matrix$(MENUM)py.so  P1_gc_ttxc/matrix$(MENUM)py.so  P1_gd_ttxd/matrix$(MENUM)py.so  P1_gb_ttxb/matrix$(MENUM)py.so  P1_gux_ttxux/matrix$(MENUM)py.so  P1_gcx_ttxcx/matrix$(MENUM)py.so  P1_gdx_ttxdx/matrix$(MENUM)py.so  P1_gbx_ttxbx/matrix$(MENUM)py.so  P1_uux_ttxg/matrix$(MENUM)py.so  P1_ccx_ttxg/matrix$(MENUM)py.so  P1_ddx_ttxg/matrix$(MENUM)py.so  P1_bbx_ttxg/matrix$(MENUM)py.so  P0_gg_ttx/matrix$(MENUM)py.so  P0_uux_ttx/matrix$(MENUM)py.so  P0_ccx_ttx/matrix$(MENUM)py.so  P0_ddx_ttx/matrix$(MENUM)py.so  P0_bbx_ttx/matrix$(MENUM)py.so 
	echo 'done'