C     Diagram 1
      DATA MAPCONFIG(1)/1/
      DATA (IFOREST(I,-1,1),I=1,2)/4,3/
      DATA (SPROP(I,-1,1),I=1,1)/21/
      DATA TPRID(-1,1)/0/
      DATA (IFOREST(I,-2,1),I=1,2)/5,-1/
      DATA (SPROP(I,-2,1),I=1,1)/21/
      DATA TPRID(-2,1)/0/
C     Diagram 2
      DATA MAPCONFIG(2)/2/
      DATA (IFOREST(I,-1,2),I=1,2)/4,3/
      DATA (SPROP(I,-1,2),I=1,1)/21/
      DATA TPRID(-1,2)/0/
      DATA (IFOREST(I,-2,2),I=1,2)/5,-1/
      DATA (SPROP(I,-2,2),I=1,1)/21/
      DATA TPRID(-2,2)/0/
C     Diagram 3
      DATA MAPCONFIG(3)/3/
      DATA (IFOREST(I,-1,3),I=1,2)/5,3/
      DATA (SPROP(I,-1,3),I=1,1)/6/
      DATA TPRID(-1,3)/0/
      DATA (IFOREST(I,-2,3),I=1,2)/4,-1/
      DATA (SPROP(I,-2,3),I=1,1)/21/
      DATA TPRID(-2,3)/0/
C     Diagram 4
      DATA MAPCONFIG(4)/4/
      DATA (IFOREST(I,-1,4),I=1,2)/5,3/
      DATA (SPROP(I,-1,4),I=1,1)/6/
      DATA TPRID(-1,4)/0/
      DATA (IFOREST(I,-2,4),I=1,2)/4,-1/
      DATA (SPROP(I,-2,4),I=1,1)/21/
      DATA TPRID(-2,4)/0/
C     Diagram 5
      DATA MAPCONFIG(5)/5/
      DATA (IFOREST(I,-1,5),I=1,2)/5,3/
      DATA (SPROP(I,-1,5),I=1,1)/6/
      DATA TPRID(-1,5)/0/
      DATA (IFOREST(I,-2,5),I=1,2)/4,-1/
      DATA (SPROP(I,-2,5),I=1,1)/21/
      DATA TPRID(-2,5)/0/
C     Diagram 6
      DATA MAPCONFIG(6)/6/
      DATA (IFOREST(I,-1,6),I=1,2)/5,4/
      DATA (SPROP(I,-1,6),I=1,1)/-6/
      DATA TPRID(-1,6)/0/
      DATA (IFOREST(I,-2,6),I=1,2)/-1,3/
      DATA (SPROP(I,-2,6),I=1,1)/21/
      DATA TPRID(-2,6)/0/
C     Diagram 7
      DATA MAPCONFIG(7)/7/
      DATA (IFOREST(I,-1,7),I=1,2)/5,4/
      DATA (SPROP(I,-1,7),I=1,1)/-6/
      DATA TPRID(-1,7)/0/
      DATA (IFOREST(I,-2,7),I=1,2)/-1,3/
      DATA (SPROP(I,-2,7),I=1,1)/21/
      DATA TPRID(-2,7)/0/
C     Diagram 8
      DATA MAPCONFIG(8)/8/
      DATA (IFOREST(I,-1,8),I=1,2)/5,4/
      DATA (SPROP(I,-1,8),I=1,1)/-6/
      DATA TPRID(-1,8)/0/
      DATA (IFOREST(I,-2,8),I=1,2)/-1,3/
      DATA (SPROP(I,-2,8),I=1,1)/21/
      DATA TPRID(-2,8)/0/
C     Diagram 10
      DATA MAPCONFIG(9)/10/
      DATA (IFOREST(I,-1,9),I=1,2)/1,3/
      DATA TPRID(-1,9)/6/
      DATA (SPROP(I,-1,9),I=1,1)/0/
      DATA (IFOREST(I,-2,9),I=1,2)/-1,5/
      DATA TPRID(-2,9)/6/
      DATA (SPROP(I,-2,9),I=1,1)/0/
      DATA (IFOREST(I,-3,9),I=1,2)/-2,4/
C     Diagram 11
      DATA MAPCONFIG(10)/11/
      DATA (IFOREST(I,-1,10),I=1,2)/1,3/
      DATA TPRID(-1,10)/6/
      DATA (SPROP(I,-1,10),I=1,1)/0/
      DATA (IFOREST(I,-2,10),I=1,2)/-1,5/
      DATA TPRID(-2,10)/6/
      DATA (SPROP(I,-2,10),I=1,1)/0/
      DATA (IFOREST(I,-3,10),I=1,2)/-2,4/
C     Diagram 12
      DATA MAPCONFIG(11)/12/
      DATA (IFOREST(I,-1,11),I=1,2)/1,3/
      DATA TPRID(-1,11)/6/
      DATA (SPROP(I,-1,11),I=1,1)/0/
      DATA (IFOREST(I,-2,11),I=1,2)/-1,5/
      DATA TPRID(-2,11)/6/
      DATA (SPROP(I,-2,11),I=1,1)/0/
      DATA (IFOREST(I,-3,11),I=1,2)/-2,4/
C     Diagram 13
      DATA MAPCONFIG(12)/13/
      DATA (IFOREST(I,-1,12),I=1,2)/1,3/
      DATA TPRID(-1,12)/6/
      DATA (SPROP(I,-1,12),I=1,1)/0/
      DATA (IFOREST(I,-2,12),I=1,2)/-1,5/
      DATA TPRID(-2,12)/6/
      DATA (SPROP(I,-2,12),I=1,1)/0/
      DATA (IFOREST(I,-3,12),I=1,2)/-2,4/
C     Diagram 14
      DATA MAPCONFIG(13)/14/
      DATA (IFOREST(I,-1,13),I=1,2)/1,3/
      DATA TPRID(-1,13)/6/
      DATA (SPROP(I,-1,13),I=1,1)/0/
      DATA (IFOREST(I,-2,13),I=1,2)/-1,4/
      DATA TPRID(-2,13)/21/
      DATA (SPROP(I,-2,13),I=1,1)/0/
      DATA (IFOREST(I,-3,13),I=1,2)/-2,5/
C     Diagram 15
      DATA MAPCONFIG(14)/15/
      DATA (IFOREST(I,-1,14),I=1,2)/1,3/
      DATA TPRID(-1,14)/6/
      DATA (SPROP(I,-1,14),I=1,1)/0/
      DATA (IFOREST(I,-2,14),I=1,2)/-1,4/
      DATA TPRID(-2,14)/21/
      DATA (SPROP(I,-2,14),I=1,1)/0/
      DATA (IFOREST(I,-3,14),I=1,2)/-2,5/
C     Diagram 16
      DATA MAPCONFIG(15)/16/
      DATA (IFOREST(I,-1,15),I=1,2)/1,3/
      DATA TPRID(-1,15)/6/
      DATA (SPROP(I,-1,15),I=1,1)/0/
      DATA (IFOREST(I,-2,15),I=1,2)/-1,4/
      DATA TPRID(-2,15)/21/
      DATA (SPROP(I,-2,15),I=1,1)/0/
      DATA (IFOREST(I,-3,15),I=1,2)/-2,5/
C     Diagram 17
      DATA MAPCONFIG(16)/17/
      DATA (IFOREST(I,-1,16),I=1,2)/5,4/
      DATA (SPROP(I,-1,16),I=1,1)/-6/
      DATA TPRID(-1,16)/0/
      DATA (IFOREST(I,-2,16),I=1,2)/1,3/
      DATA TPRID(-2,16)/6/
      DATA (SPROP(I,-2,16),I=1,1)/0/
      DATA (IFOREST(I,-3,16),I=1,2)/-2,-1/
C     Diagram 18
      DATA MAPCONFIG(17)/18/
      DATA (IFOREST(I,-1,17),I=1,2)/5,4/
      DATA (SPROP(I,-1,17),I=1,1)/-6/
      DATA TPRID(-1,17)/0/
      DATA (IFOREST(I,-2,17),I=1,2)/1,3/
      DATA TPRID(-2,17)/6/
      DATA (SPROP(I,-2,17),I=1,1)/0/
      DATA (IFOREST(I,-3,17),I=1,2)/-2,-1/
C     Diagram 19
      DATA MAPCONFIG(18)/19/
      DATA (IFOREST(I,-1,18),I=1,2)/5,4/
      DATA (SPROP(I,-1,18),I=1,1)/-6/
      DATA TPRID(-1,18)/0/
      DATA (IFOREST(I,-2,18),I=1,2)/1,3/
      DATA TPRID(-2,18)/6/
      DATA (SPROP(I,-2,18),I=1,1)/0/
      DATA (IFOREST(I,-3,18),I=1,2)/-2,-1/
C     Diagram 20
      DATA MAPCONFIG(19)/20/
      DATA (IFOREST(I,-1,19),I=1,2)/5,4/
      DATA (SPROP(I,-1,19),I=1,1)/-6/
      DATA TPRID(-1,19)/0/
      DATA (IFOREST(I,-2,19),I=1,2)/1,3/
      DATA TPRID(-2,19)/6/
      DATA (SPROP(I,-2,19),I=1,1)/0/
      DATA (IFOREST(I,-3,19),I=1,2)/-2,-1/
C     Diagram 22
      DATA MAPCONFIG(20)/22/
      DATA (IFOREST(I,-1,20),I=1,2)/1,4/
      DATA TPRID(-1,20)/6/
      DATA (SPROP(I,-1,20),I=1,1)/0/
      DATA (IFOREST(I,-2,20),I=1,2)/-1,5/
      DATA TPRID(-2,20)/6/
      DATA (SPROP(I,-2,20),I=1,1)/0/
      DATA (IFOREST(I,-3,20),I=1,2)/-2,3/
C     Diagram 23
      DATA MAPCONFIG(21)/23/
      DATA (IFOREST(I,-1,21),I=1,2)/1,4/
      DATA TPRID(-1,21)/6/
      DATA (SPROP(I,-1,21),I=1,1)/0/
      DATA (IFOREST(I,-2,21),I=1,2)/-1,5/
      DATA TPRID(-2,21)/6/
      DATA (SPROP(I,-2,21),I=1,1)/0/
      DATA (IFOREST(I,-3,21),I=1,2)/-2,3/
C     Diagram 24
      DATA MAPCONFIG(22)/24/
      DATA (IFOREST(I,-1,22),I=1,2)/1,4/
      DATA TPRID(-1,22)/6/
      DATA (SPROP(I,-1,22),I=1,1)/0/
      DATA (IFOREST(I,-2,22),I=1,2)/-1,5/
      DATA TPRID(-2,22)/6/
      DATA (SPROP(I,-2,22),I=1,1)/0/
      DATA (IFOREST(I,-3,22),I=1,2)/-2,3/
C     Diagram 25
      DATA MAPCONFIG(23)/25/
      DATA (IFOREST(I,-1,23),I=1,2)/1,4/
      DATA TPRID(-1,23)/6/
      DATA (SPROP(I,-1,23),I=1,1)/0/
      DATA (IFOREST(I,-2,23),I=1,2)/-1,5/
      DATA TPRID(-2,23)/6/
      DATA (SPROP(I,-2,23),I=1,1)/0/
      DATA (IFOREST(I,-3,23),I=1,2)/-2,3/
C     Diagram 26
      DATA MAPCONFIG(24)/26/
      DATA (IFOREST(I,-1,24),I=1,2)/1,4/
      DATA TPRID(-1,24)/6/
      DATA (SPROP(I,-1,24),I=1,1)/0/
      DATA (IFOREST(I,-2,24),I=1,2)/-1,3/
      DATA TPRID(-2,24)/21/
      DATA (SPROP(I,-2,24),I=1,1)/0/
      DATA (IFOREST(I,-3,24),I=1,2)/-2,5/
C     Diagram 27
      DATA MAPCONFIG(25)/27/
      DATA (IFOREST(I,-1,25),I=1,2)/1,4/
      DATA TPRID(-1,25)/6/
      DATA (SPROP(I,-1,25),I=1,1)/0/
      DATA (IFOREST(I,-2,25),I=1,2)/-1,3/
      DATA TPRID(-2,25)/21/
      DATA (SPROP(I,-2,25),I=1,1)/0/
      DATA (IFOREST(I,-3,25),I=1,2)/-2,5/
C     Diagram 28
      DATA MAPCONFIG(26)/28/
      DATA (IFOREST(I,-1,26),I=1,2)/1,4/
      DATA TPRID(-1,26)/6/
      DATA (SPROP(I,-1,26),I=1,1)/0/
      DATA (IFOREST(I,-2,26),I=1,2)/-1,3/
      DATA TPRID(-2,26)/21/
      DATA (SPROP(I,-2,26),I=1,1)/0/
      DATA (IFOREST(I,-3,26),I=1,2)/-2,5/
C     Diagram 29
      DATA MAPCONFIG(27)/29/
      DATA (IFOREST(I,-1,27),I=1,2)/5,3/
      DATA (SPROP(I,-1,27),I=1,1)/6/
      DATA TPRID(-1,27)/0/
      DATA (IFOREST(I,-2,27),I=1,2)/1,4/
      DATA TPRID(-2,27)/6/
      DATA (SPROP(I,-2,27),I=1,1)/0/
      DATA (IFOREST(I,-3,27),I=1,2)/-2,-1/
C     Diagram 30
      DATA MAPCONFIG(28)/30/
      DATA (IFOREST(I,-1,28),I=1,2)/5,3/
      DATA (SPROP(I,-1,28),I=1,1)/6/
      DATA TPRID(-1,28)/0/
      DATA (IFOREST(I,-2,28),I=1,2)/1,4/
      DATA TPRID(-2,28)/6/
      DATA (SPROP(I,-2,28),I=1,1)/0/
      DATA (IFOREST(I,-3,28),I=1,2)/-2,-1/
C     Diagram 31
      DATA MAPCONFIG(29)/31/
      DATA (IFOREST(I,-1,29),I=1,2)/5,3/
      DATA (SPROP(I,-1,29),I=1,1)/6/
      DATA TPRID(-1,29)/0/
      DATA (IFOREST(I,-2,29),I=1,2)/1,4/
      DATA TPRID(-2,29)/6/
      DATA (SPROP(I,-2,29),I=1,1)/0/
      DATA (IFOREST(I,-3,29),I=1,2)/-2,-1/
C     Diagram 32
      DATA MAPCONFIG(30)/32/
      DATA (IFOREST(I,-1,30),I=1,2)/5,3/
      DATA (SPROP(I,-1,30),I=1,1)/6/
      DATA TPRID(-1,30)/0/
      DATA (IFOREST(I,-2,30),I=1,2)/1,4/
      DATA TPRID(-2,30)/6/
      DATA (SPROP(I,-2,30),I=1,1)/0/
      DATA (IFOREST(I,-3,30),I=1,2)/-2,-1/
C     Diagram 34
      DATA MAPCONFIG(31)/34/
      DATA (IFOREST(I,-1,31),I=1,2)/1,5/
      DATA TPRID(-1,31)/21/
      DATA (SPROP(I,-1,31),I=1,1)/0/
      DATA (IFOREST(I,-2,31),I=1,2)/-1,4/
      DATA TPRID(-2,31)/6/
      DATA (SPROP(I,-2,31),I=1,1)/0/
      DATA (IFOREST(I,-3,31),I=1,2)/-2,3/
C     Diagram 35
      DATA MAPCONFIG(32)/35/
      DATA (IFOREST(I,-1,32),I=1,2)/1,5/
      DATA TPRID(-1,32)/21/
      DATA (SPROP(I,-1,32),I=1,1)/0/
      DATA (IFOREST(I,-2,32),I=1,2)/-1,4/
      DATA TPRID(-2,32)/6/
      DATA (SPROP(I,-2,32),I=1,1)/0/
      DATA (IFOREST(I,-3,32),I=1,2)/-2,3/
C     Diagram 36
      DATA MAPCONFIG(33)/36/
      DATA (IFOREST(I,-1,33),I=1,2)/1,5/
      DATA TPRID(-1,33)/21/
      DATA (SPROP(I,-1,33),I=1,1)/0/
      DATA (IFOREST(I,-2,33),I=1,2)/-1,4/
      DATA TPRID(-2,33)/6/
      DATA (SPROP(I,-2,33),I=1,1)/0/
      DATA (IFOREST(I,-3,33),I=1,2)/-2,3/
C     Diagram 37
      DATA MAPCONFIG(34)/37/
      DATA (IFOREST(I,-1,34),I=1,2)/1,5/
      DATA TPRID(-1,34)/21/
      DATA (SPROP(I,-1,34),I=1,1)/0/
      DATA (IFOREST(I,-2,34),I=1,2)/-1,3/
      DATA TPRID(-2,34)/6/
      DATA (SPROP(I,-2,34),I=1,1)/0/
      DATA (IFOREST(I,-3,34),I=1,2)/-2,4/
C     Diagram 38
      DATA MAPCONFIG(35)/38/
      DATA (IFOREST(I,-1,35),I=1,2)/1,5/
      DATA TPRID(-1,35)/21/
      DATA (SPROP(I,-1,35),I=1,1)/0/
      DATA (IFOREST(I,-2,35),I=1,2)/-1,3/
      DATA TPRID(-2,35)/6/
      DATA (SPROP(I,-2,35),I=1,1)/0/
      DATA (IFOREST(I,-3,35),I=1,2)/-2,4/
C     Diagram 39
      DATA MAPCONFIG(36)/39/
      DATA (IFOREST(I,-1,36),I=1,2)/1,5/
      DATA TPRID(-1,36)/21/
      DATA (SPROP(I,-1,36),I=1,1)/0/
      DATA (IFOREST(I,-2,36),I=1,2)/-1,3/
      DATA TPRID(-2,36)/6/
      DATA (SPROP(I,-2,36),I=1,1)/0/
      DATA (IFOREST(I,-3,36),I=1,2)/-2,4/
C     Diagram 40
      DATA MAPCONFIG(37)/40/
      DATA (IFOREST(I,-1,37),I=1,2)/4,3/
      DATA (SPROP(I,-1,37),I=1,1)/21/
      DATA TPRID(-1,37)/0/
      DATA (IFOREST(I,-2,37),I=1,2)/1,5/
      DATA TPRID(-2,37)/21/
      DATA (SPROP(I,-2,37),I=1,1)/0/
      DATA (IFOREST(I,-3,37),I=1,2)/-2,-1/
C     Diagram 41
      DATA MAPCONFIG(38)/41/
      DATA (IFOREST(I,-1,38),I=1,2)/4,3/
      DATA (SPROP(I,-1,38),I=1,1)/21/
      DATA TPRID(-1,38)/0/
      DATA (IFOREST(I,-2,38),I=1,2)/1,5/
      DATA TPRID(-2,38)/21/
      DATA (SPROP(I,-2,38),I=1,1)/0/
      DATA (IFOREST(I,-3,38),I=1,2)/-2,-1/
C     Diagram 43
      DATA MAPCONFIG(39)/43/
      DATA (IFOREST(I,-1,39),I=1,2)/5,4/
      DATA (SPROP(I,-1,39),I=1,1)/-6/
      DATA TPRID(-1,39)/0/
      DATA (IFOREST(I,-2,39),I=1,2)/1,-1/
      DATA TPRID(-2,39)/6/
      DATA (SPROP(I,-2,39),I=1,1)/0/
      DATA (IFOREST(I,-3,39),I=1,2)/-2,3/
C     Diagram 44
      DATA MAPCONFIG(40)/44/
      DATA (IFOREST(I,-1,40),I=1,2)/5,4/
      DATA (SPROP(I,-1,40),I=1,1)/-6/
      DATA TPRID(-1,40)/0/
      DATA (IFOREST(I,-2,40),I=1,2)/1,-1/
      DATA TPRID(-2,40)/6/
      DATA (SPROP(I,-2,40),I=1,1)/0/
      DATA (IFOREST(I,-3,40),I=1,2)/-2,3/
C     Diagram 45
      DATA MAPCONFIG(41)/45/
      DATA (IFOREST(I,-1,41),I=1,2)/5,4/
      DATA (SPROP(I,-1,41),I=1,1)/-6/
      DATA TPRID(-1,41)/0/
      DATA (IFOREST(I,-2,41),I=1,2)/1,-1/
      DATA TPRID(-2,41)/6/
      DATA (SPROP(I,-2,41),I=1,1)/0/
      DATA (IFOREST(I,-3,41),I=1,2)/-2,3/
C     Diagram 46
      DATA MAPCONFIG(42)/46/
      DATA (IFOREST(I,-1,42),I=1,2)/5,4/
      DATA (SPROP(I,-1,42),I=1,1)/-6/
      DATA TPRID(-1,42)/0/
      DATA (IFOREST(I,-2,42),I=1,2)/1,-1/
      DATA TPRID(-2,42)/6/
      DATA (SPROP(I,-2,42),I=1,1)/0/
      DATA (IFOREST(I,-3,42),I=1,2)/-2,3/
C     Diagram 47
      DATA MAPCONFIG(43)/47/
      DATA (IFOREST(I,-1,43),I=1,2)/5,3/
      DATA (SPROP(I,-1,43),I=1,1)/6/
      DATA TPRID(-1,43)/0/
      DATA (IFOREST(I,-2,43),I=1,2)/1,-1/
      DATA TPRID(-2,43)/6/
      DATA (SPROP(I,-2,43),I=1,1)/0/
      DATA (IFOREST(I,-3,43),I=1,2)/-2,4/
C     Diagram 48
      DATA MAPCONFIG(44)/48/
      DATA (IFOREST(I,-1,44),I=1,2)/5,3/
      DATA (SPROP(I,-1,44),I=1,1)/6/
      DATA TPRID(-1,44)/0/
      DATA (IFOREST(I,-2,44),I=1,2)/1,-1/
      DATA TPRID(-2,44)/6/
      DATA (SPROP(I,-2,44),I=1,1)/0/
      DATA (IFOREST(I,-3,44),I=1,2)/-2,4/
C     Diagram 49
      DATA MAPCONFIG(45)/49/
      DATA (IFOREST(I,-1,45),I=1,2)/5,3/
      DATA (SPROP(I,-1,45),I=1,1)/6/
      DATA TPRID(-1,45)/0/
      DATA (IFOREST(I,-2,45),I=1,2)/1,-1/
      DATA TPRID(-2,45)/6/
      DATA (SPROP(I,-2,45),I=1,1)/0/
      DATA (IFOREST(I,-3,45),I=1,2)/-2,4/
C     Diagram 50
      DATA MAPCONFIG(46)/50/
      DATA (IFOREST(I,-1,46),I=1,2)/5,3/
      DATA (SPROP(I,-1,46),I=1,1)/6/
      DATA TPRID(-1,46)/0/
      DATA (IFOREST(I,-2,46),I=1,2)/1,-1/
      DATA TPRID(-2,46)/6/
      DATA (SPROP(I,-2,46),I=1,1)/0/
      DATA (IFOREST(I,-3,46),I=1,2)/-2,4/
C     Diagram 51
      DATA MAPCONFIG(47)/51/
      DATA (IFOREST(I,-1,47),I=1,2)/4,3/
      DATA (SPROP(I,-1,47),I=1,1)/21/
      DATA TPRID(-1,47)/0/
      DATA (IFOREST(I,-2,47),I=1,2)/1,-1/
      DATA TPRID(-2,47)/21/
      DATA (SPROP(I,-2,47),I=1,1)/0/
      DATA (IFOREST(I,-3,47),I=1,2)/-2,5/
C     Diagram 52
      DATA MAPCONFIG(48)/52/
      DATA (IFOREST(I,-1,48),I=1,2)/4,3/
      DATA (SPROP(I,-1,48),I=1,1)/21/
      DATA TPRID(-1,48)/0/
      DATA (IFOREST(I,-2,48),I=1,2)/1,-1/
      DATA TPRID(-2,48)/21/
      DATA (SPROP(I,-2,48),I=1,1)/0/
      DATA (IFOREST(I,-3,48),I=1,2)/-2,5/
C     Number of configs
      DATA MAPCONFIG(0)/48/
