
# For python linking (require f2py part of numpy)
ifeq ($(origin MENUM),undefined)
  MENUM=2
endif
P0_tx_bxwm_wm_emvex/matrix$(MENUM)py.so:
	cd P0_tx_bxwm_wm_emvex;make matrix$(MENUM)py.so
P0_tx_bxwm_wm_mumvmx/matrix$(MENUM)py.so:
	cd P0_tx_bxwm_wm_mumvmx;make matrix$(MENUM)py.so
P0_tx_bxwm_wm_tamvtx/matrix$(MENUM)py.so:
	cd P0_tx_bxwm_wm_tamvtx;make matrix$(MENUM)py.so
P1_t_bwp_wp_epve/matrix$(MENUM)py.so:
	cd P1_t_bwp_wp_epve;make matrix$(MENUM)py.so
P1_t_bwp_wp_mupvm/matrix$(MENUM)py.so:
	cd P1_t_bwp_wp_mupvm;make matrix$(MENUM)py.so
P1_t_bwp_wp_tapvt/matrix$(MENUM)py.so:
	cd P1_t_bwp_wp_tapvt;make matrix$(MENUM)py.so
all:  P0_tx_bxwm_wm_emvex/matrix$(MENUM)py.so  P0_tx_bxwm_wm_mumvmx/matrix$(MENUM)py.so  P0_tx_bxwm_wm_tamvtx/matrix$(MENUM)py.so  P1_t_bwp_wp_epve/matrix$(MENUM)py.so  P1_t_bwp_wp_mupvm/matrix$(MENUM)py.so  P1_t_bwp_wp_tapvt/matrix$(MENUM)py.so 
	echo 'done'