ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFTatNLO-LO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_358 = ', GC_358
      WRITE(*,2) 'GC_360 = ', GC_360
      WRITE(*,2) 'GC_10 = ', GC_10
      WRITE(*,2) 'GC_11 = ', GC_11
      WRITE(*,2) 'GC_12 = ', GC_12
      WRITE(*,2) 'GC_109 = ', GC_109
      WRITE(*,2) 'GC_110 = ', GC_110
      WRITE(*,2) 'GC_112 = ', GC_112
      WRITE(*,2) 'GC_113 = ', GC_113
      WRITE(*,2) 'GC_30 = ', GC_30
      WRITE(*,2) 'GC_31 = ', GC_31
      WRITE(*,2) 'GC_32 = ', GC_32
      WRITE(*,2) 'GC_34 = ', GC_34
      WRITE(*,2) 'GC_35 = ', GC_35
      WRITE(*,2) 'GC_71 = ', GC_71
      WRITE(*,2) 'GC_72 = ', GC_72
      WRITE(*,2) 'GC_83 = ', GC_83
      WRITE(*,2) 'GC_85 = ', GC_85
      WRITE(*,2) 'GC_86 = ', GC_86
      WRITE(*,2) 'GC_87 = ', GC_87
      WRITE(*,2) 'GC_88 = ', GC_88
      WRITE(*,2) 'GC_89 = ', GC_89
      WRITE(*,2) 'GC_90 = ', GC_90
